### ISSUE TITLE
Needs color support

### ISSUE THREAD

**Issue by kurtextrem** [tholman/console-dot-frog#3]
A black&white frog just doesn't make the cut.

**Comment by shvelo** [comment]
What about a green frog #4

**Comment by Rossolson** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/console#Styling_console_output

**Comment by cpeddecord** [comment]
I've just created a potential fork for rainbow frogs, but don't want to fracture the community too much. Let me know if there's interest as it's very important for my team to have rainbows.

**Comment by zacparker** [comment]
👍 rainbowfrog

**Comment by tholman** [comment]
Its a green frog for now! 💃
